<!-- Message de notification -->

<!-- Code HTML à écrire -->


<!-- Liste des aliments -->
<section>
    <h2><i class="fas fa-shopping-cart"></i> Passer une commande</h2>
    <form action="" method="">
        <fieldset>
            <legend>Ajouter un article</legend>
            <table>
                <tr>
                    <td><label for="products">Nom :</label></td>
                    <td>
                        <select name="products" id="products">
                        <?php foreach ($meals as $meal): ?>
                            <option value="<?= $meal["Id"] ?>"><?= $meal["Name"] ?></option>
                        <?php endforeach; ?>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <ul id="displayProduct">

                        </ul>
                    </td>
                </tr>
                <tr>
                    <td><label for="quantity">Quantity :</label></td>
                    <td><input type="number" id="quantity" name="quantity"></td>
                </tr>
            </table>
            <button type="button" id="addProduct">Ajouter</button>
        </fieldset>
        <fieldset>
            <legend>Récapitulatif de la commande</legend>
            <table id="recapCommande">
                <tr>
                    <td></td>
                    <td>Quantité</td>
                    <td>Produit</td>
                    <td>Prix Unitaire</td>
                    <td>Prix Total</td>
                </tr>
                <tbody id="contenuProduct">

                </tbody>
            </table>
        </fieldset>
        <button type="button" id="submit">Valider la commande</button>
        <button type="reset">Annuler</button>
    </form>
</section>