<!-- Message de notification -->

<!-- Code HTML à écrire -->


<!-- Liste des aliments -->
<section>
    <h2><i class="fas fa-lock"></i> Se connecter avec un compte utilisateur</h2>
    <form action="<?= $requestUrl ?>/login" method="POST">
        <fieldset>
            <legend><i class="fas fa-lock"></i> Information d'authentification</legend>
            <table>
                <tr>
                    <td><label for="email">E-mail :</label></td>
                    <td><input type="email" id="email" name="email" /></td>
                </tr>
                <tr>
                    <td><label for="password">Mot de passe :</label></td>
                    <td><input type="password" id="password" name="password" /></td>
                </tr>
            </table>
        </fieldset>
        <button type="submit">Connexion</button>
        <button type="reset">Annuler</button>
    </form>
</section>